# TODO: This is generated by AI and needs further consideration!!
"""
    contract_sparse_support(vars_a, supp_a, vars_b, supp_b, contract_var, limit)

Contract two tensors represented by sparse supports (list of valid configurations).
Returns (new_vars, new_support) or (nothing, nothing) if result exceeds limit.
"""
function contract_sparse_support(vars_a::Vector{Int}, supp_a::Vector{Int}, 
                               vars_b::Vector{Int}, supp_b::Vector{Int}, 
                               contract_var::Int, limit::Int)
    # 1. Align variables
    # We need to match rows in supp_a where var == val with rows in supp_b where var == val
    
    # Locate contract_var index in both
    idx_a = findfirst(==(contract_var), vars_a)
    idx_b = findfirst(==(contract_var), vars_b)
    
    # Determine output variables (sorted for consistency)
    out_vars = sort!(unique(vcat(vars_a, vars_b)))
    filter!(!=(contract_var), out_vars)
    
    # Maps to map bits from A/B to Output
    # We pre-calculate bit masks/shifts for speed
    # (Simplified logical version below for clarity, can be optimized with bit-twiddling)
    
    new_supp = Int[]
    sizehint!(new_supp, limit)

    # Convert supports to structured tables for joining
    # This is a Hash Join operation
    # Key: value of contract_var, Value: list of (other_vars_config)
    
    # Since var is boolean, we just split support into two buckets: var=0 and var=1
    
    # Helper to extract the bit at `idx` and the rest of the config
    @inline function split_config(conf, idx, total_vars)
        bit = (conf >> (idx-1)) & 1
        # Mask out the bit at idx to get "rest" (this logic depends on bit packing order)
        # Here we assume a simple join is easier:
        return bit
    end

    # Naive Join (O(|A|*|B|)) - acceptable since |A|,|B| <= limit (small)
    # Optimizable to O(|A|+|B|) with hashing, but limit is small (e.g. 128)
    
    mask_a = 1 << (idx_a - 1)
    mask_b = 1 << (idx_b - 1)
    
    for conf_a in supp_a
        val_a = (conf_a & mask_a) != 0
        
        for conf_b in supp_b
            val_b = (conf_b & mask_b) != 0
            
            # Key condition: The shared variable must match
            if val_a == val_b
                # Merge configurations
                # We need to construct the new integer config based on out_vars
                new_conf = 0
                
                # Reconstruct A's contribution
                for (i, v) in enumerate(vars_a)
                    v == contract_var && continue
                    bit = (conf_a >> (i-1)) & 1
                    # Map to position in out_vars
                    target_pos = findfirst(==(v), out_vars)
                    new_conf |= (bit << (target_pos-1))
                end
                
                # Reconstruct B's contribution
                for (i, v) in enumerate(vars_b)
                    v == contract_var && continue
                    bit = (conf_b >> (i-1)) & 1
                    target_pos = findfirst(==(v), out_vars)
                    new_conf |= (bit << (target_pos-1))
                end
                
                # Store unique configs
                if !(new_conf in new_supp)
                    push!(new_supp, new_conf)
                    if length(new_supp) > limit
                        return nothing, nothing # Exceeded limit
                    end
                end
            end
        end
    end
    
    return out_vars, new_supp
end

"""
    simplify_tensor_network_optimized(var_num, tensors_to_vars, tensor_data; support_limit=128)

Optimized simplification using a queue and sparse contraction.
"""
function simplify_tensor_network(var_num::Int, 
                                tensors_to_vars::Vector{Vector{Int}}, 
                                tensor_data::Vector{BitVector}; # Input is dense
                                support_limit::Int=128)
    
    # 1. Convert all initial dense BitVectors to Sparse Supports (Vector{Int})
    # This is much faster to work with for small gates
    current_supports = Vector{Vector{Int}}(undef, length(tensor_data))
    for i in 1:length(tensor_data)
        # Convert bitvector index to integer config (0-based)
        current_supports[i] = [idx-1 for (idx, val) in enumerate(tensor_data[i]) if val]
    end
    
    # 2. Build Adjacency List (Variable -> Set of Tensor IDs)
    v2t = [Set{Int}() for _ in 1:var_num]
    active_tensors = Set{Int}()
    
    for (tidx, vars) in enumerate(tensors_to_vars)
        push!(active_tensors, tidx)
        for v in vars
            push!(v2t[v], tidx)
        end
    end
    
    # 3. Initialize Queue with degree-2 variables
    queue = Int[]
    for v in 1:var_num
        if length(v2t[v]) == 2
            push!(queue, v)
        end
    end
    
    # Track tensor validity to handle lazy deletion
    # We append new tensors to the list, so we need a dynamic way to track them
    # We will just append to `tensors_to_vars` and `current_supports`
    
    while !isempty(queue)
        var = popfirst!(queue)
        
        # Verify degree is still 2 (topology might have changed)
        if length(v2t[var]) != 2
            continue
        end
        
        # Get the two tensors to merge
        t_ids = collect(v2t[var])
        tidx_a, tidx_b = t_ids[1], t_ids[2]
        
        # Check if they are still active
        if !(tidx_a in active_tensors) || !(tidx_b in active_tensors)
            continue
        end
        
        # Perform contraction
        res = contract_sparse_support(
            tensors_to_vars[tidx_a], current_supports[tidx_a],
            tensors_to_vars[tidx_b], current_supports[tidx_b],
            var, support_limit
        )
        
        if isnothing(res)
            # Result too large, cannot merge. Skip this variable.
            # It will remain degree 2 but unmergeable.
            continue
        end
        
        new_vars, new_supp = res
        
        # === SUCCESSFUL MERGE ===
        
        # 1. Deactivate old tensors
        delete!(active_tensors, tidx_a)
        delete!(active_tensors, tidx_b)
        
        # 2. Register new tensor
        push!(tensors_to_vars, new_vars)
        push!(current_supports, new_supp)
        new_tidx = length(tensors_to_vars)
        push!(active_tensors, new_tidx)
        
        # 3. Update Adjacency Graph (Locally!)
        # Remove old tensors from neighbors
        for v in tensors_to_vars[tidx_a]; delete!(v2t[v], tidx_a); end
        for v in tensors_to_vars[tidx_b]; delete!(v2t[v], tidx_b); end
        
        # Add new tensor to neighbors
        for v in new_vars
            push!(v2t[v], new_tidx)
            # If a neighbor becomes degree 2 due to this merge, add to queue
            # (Note: merge usually reduces degree or keeps it same, but neighbors of neighbors might change context)
            if length(v2t[v]) == 2
                push!(queue, v)
            end
        end
        
        # The contract_var is now eliminated (degree 0), remove it from map
        empty!(v2t[var])
    end
    
    # 4. Convert back to output format
    # Only return active tensors
    final_indices = collect(active_tensors)
    final_vars = tensors_to_vars[final_indices]
    
    # Convert supports back to BitVectors for your solver compatibility
    final_data = BitVector[]
    for idx in final_indices
        vars = tensors_to_vars[idx]
        supp = current_supports[idx]
        
        # 1 << N
        len = 1 << length(vars)
        bv = falses(len)
        for conf in supp
            bv[conf + 1] = true
        end
        push!(final_data, bv)
    end
    
    return final_vars, final_data
end